/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_otc_tsdv_GraphFilterJNILib */

#ifndef _Included_com_intel_otc_tsdv_GraphFilterJNILib
#define _Included_com_intel_otc_tsdv_GraphFilterJNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_otc_tsdv_GraphFilterJNILib
 * Method:    initNative
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_otc_tsdv_GraphFilterJNILib_initNative
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_intel_otc_tsdv_GraphFilterJNILib
 * Method:    addDataNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_otc_tsdv_GraphFilterJNILib_addDataNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_intel_otc_tsdv_GraphFilterJNILib
 * Method:    getDataNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_otc_tsdv_GraphFilterJNILib_getDataNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
